"""Currency for transactions

Revision ID: 0401e3896700
Revises: 28bf02666f59
Create Date: 2017-05-29 21:57:45.065322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0401e3896700'
down_revision = '28bf02666f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts') as batch_op:
        batch_op.create_foreign_key('account_type', 'account_types', ['type_id'], ['id'])
        batch_op.create_foreign_key('owner', 'users', ['owner_id'], ['id'])
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.add_column(sa.Column('credit_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('debit_amount', sa.Float(), nullable=True))
        batch_op.drop_column('amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False, server_default = '0'))
    with op.batch_alter_table('transactions') as batch_op:
        batch_op.alter_column('amount', server_default = None)
        batch_op.drop_column('debit_amount')
        batch_op.drop_column('credit_amount')
    with op.batch_alter_table('accounts') as batch_op:
        batch_op.drop_constraint('owner', type_='foreignkey')
        batch_op.drop_constraint('account_type', type_='foreignkey')
    # ### end Alembic commands ###
