"""Added currency to account

Revision ID: 28bf02666f59
Revises: 3fcad09e63ed
Create Date: 2017-04-27 22:21:13.799017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28bf02666f59'
down_revision = '3fcad09e63ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('currency_id', sa.Integer(), nullable=False, server_default='0'))
    with op.batch_alter_table('accounts') as batch_op:
            batch_op.alter_column('currency_id', server_default = None)
            batch_op.create_foreign_key('accounts', 'currencies', ['currency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'accounts', type_='foreignkey')
    with op.batch_alter_table('accounts') as batch_op:
            batch_op.drop_constraint('accounts', type_='foreignkey')
            batch_op.drop_column('currency_id')
    # ### end Alembic commands ###
