"""added currency

Revision ID: 3fcad09e63ed
Revises: d59736dd8faa
Create Date: 2017-04-24 23:42:19.881397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fcad09e63ed'
down_revision = 'd59736dd8faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('left_symbol', sa.Boolean(), nullable=False),
    sa.Column('space_between', sa.Boolean(), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('decimal_separator', sa.String(), nullable=False),
    sa.Column('decimal_short', sa.String(), nullable=True),
    sa.Column('group_by', sa.Integer(), nullable=False),
    sa.Column('grouping_separator', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currencies')
    # ### end Alembic commands ###
