"""Transactions

Revision ID: 6cccd2d8ea61
Revises: 73edd31eee69
Create Date: 2017-04-24 00:01:54.506247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cccd2d8ea61'
down_revision = '73edd31eee69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_transaction_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('default_transaction_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expected_date', sa.DateTime(), nullable=False),
    sa.Column('debit_date', sa.DateTime(), nullable=True),
    sa.Column('credit_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('creditor_account_id', sa.Integer(), nullable=True),
    sa.Column('debtor_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creditor_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['debtor_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['transaction_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_tag_links',
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('transaction_tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['transaction_tag_id'], ['transaction_tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_tag_links')
    op.drop_table('transactions')
    op.drop_table('transaction_types')
    op.drop_table('transaction_tags')
    op.drop_table('default_transaction_types')
    op.drop_table('default_transaction_tags')
    # ### end Alembic commands ###
