"""Added amount to transaction

Revision ID: d59736dd8faa
Revises: 6cccd2d8ea61
Create Date: 2017-04-24 21:53:44.331142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59736dd8faa'
down_revision = '6cccd2d8ea61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('amount', sa.Float(), nullable = False, server_default = '0'))
    with op.batch_alter_table('transactions') as batch_op:
            batch_op.alter_column('amount', server_default = None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions') as batch_op:
            batch_op.drop_column('amount')
    # ### end Alembic commands ###
