"""Nullable types

Revision ID: edec8846424d
Revises: 57d748d33c22
Create Date: 2017-09-07 15:01:41.329026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edec8846424d'
down_revision = '57d748d33c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_sharing_types') as batch_op:
            batch_op.alter_column('owner_id', nullable=True)
    with op.batch_alter_table('account_types') as batch_op:
            batch_op.alter_column('owner_id', nullable=True)
    with op.batch_alter_table('transaction_types') as batch_op:
            batch_op.alter_column('owner_id', nullable=True)
    with op.batch_alter_table('transaction_tags') as batch_op:
            batch_op.alter_column('owner_id', nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_sharing_types') as batch_op:
            batch_op.alter_column('owner_id', nullable=False)
    with op.batch_alter_table('account_types') as batch_op:
            batch_op.alter_column('owner_id', nullable=False)
    with op.batch_alter_table('transaction_types') as batch_op:
            batch_op.alter_column('owner_id', nullable=False)
    with op.batch_alter_table('transaction_tags') as batch_op:
            batch_op.alter_column('owner_id', nullable=False)
    # ### end Alembic commands ###
